config/routes.rb
Places2iSola::Application.routes.draw do
  get 'areas/export' => 'areas#export'
  resources :venues

  resources :areas
  

  root 'venues#index'

end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :venues
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  belongs_to :area

  validates_presence_of    :name, :address
  validates_uniqueness_of  :name, :address

  geocoded_by :address          # can also be an IP address
  after_validation :geocode     # auto-fetch coordinates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate, :if => lambda {|c| Rails.env.production?}

  protected

  def authenticate
    raise "Authentication vars not set" unless (ENV['AUTH_USERNAME'] and ENV['AUTH_PASSWORD']).present? 
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['AUTH_USERNAME'] && password == ENV['AUTH_PASSWORD']
    end
  end

end

app/controllers/areas_controller.rb
require 'create_hash'

class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
  layout nil
  layout 'application', :except => :export

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  def export
    h = CreateHash.new
    @json = h.work
    render :layout => false
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render action: 'show', status: :created, location: @area }
      else
        format.html { render action: 'new' }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name)
    end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to venues_path, notice: 'Venue was successfully created.' }
        format.json { render action: 'show', status: :created, location: @venue }
      else
        format.html { render action: 'new' }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to venues_path, notice: 'Venue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:name, :address, :sun_from, :sun_to, :area_id, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/areas/_form.html.slim
= form_for @area do |f|
  - if @area.errors.any?
    #error_explanation
      h2 = "#{pluralize(@area.errors.count, "error")} prohibited this area from being saved:"
      ul
        - @area.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit 'Save'

app/views/areas/edit.html.slim
h1 Editing area

== render 'form'

= link_to 'Show', @area
'|
= link_to 'Back', areas_path

app/views/areas/export.html.slim
= @json.html_safe

app/views/areas/index.html.slim
h1 Listing areas

table
  tr
    th Title
    th
    th
    th

  - @areas.each do |area|
    tr
      td = area.name
      td = link_to 'Show', area
      td = link_to 'Edit', edit_area_path(area)
      td = link_to 'Destroy', area, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Area', new_area_path

app/views/areas/new.html.slim
h1 New area

== render 'form'

= link_to 'Back', areas_path

app/views/areas/show.html.slim
p#notice = notice

p
  strong Title:
  = @area.name

= link_to 'Edit', edit_area_path(@area)
'|
= link_to 'Back', areas_path

app/views/layouts/application.html.slim
doctype
html
  head
    title Place2JSON
    meta content="width=(device-width,)initial-scale=1.0" name="viewport"
      = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
      = javascript_include_tag "application", "data-turbolinks-track" => true
      = csrf_meta_tags
      
  body
    .container
      = yield

app/views/venues/_form.html.slim
= simple_form_for  @venue do |f|
  - if @venue.errors.any?
    #error_explanation
      h2 = "#{pluralize(@venue.errors.count, "error")} prohibited this venue from being saved:"
      ul
        - @venue.errors.full_messages.each do |message|
          li = message

  = f.input :name
  br
  = f.input :confirmed
  br
  = f.input :address
  = f.input :sun_from
  = f.input :sun_to
  = f.input :url
  /= f.input :image_url
  br
  .field
    = f.collection_select :area_id, Area.all, :id, :name, prompt: true
    
  .actions = f.submit 'Save', class: 'btn btn-primary'

app/views/venues/edit.html.slim
h1 Editing venue

br
br
== render 'form'

= link_to 'Show', @venue
'|
= link_to 'Back', venues_path

app/views/venues/index.html.slim
h1 Listing venues

table.table.table-striped
  tr
    th Title
    th Address
    th Sun from
    th Sun to
    th Lat
    th Long
    th Area
    th URL
    th Image URL
    th Actions

  - @venues.each do |venue|
    tr
      td = venue.name
      td = venue.address
      td = venue.sun_from.strftime '%H:%M' rescue nil  
      td = venue.sun_to.strftime '%H:%M'   rescue nil
      td = venue.latitude
      td = venue.longitude
      td = venue.area.name rescue nil
      td = venue.url
      td = image_tag venue.image_url
      td
        btn-group
          = link_to 'Show', venue, class: 'btn btn-mini'
          = link_to 'Edit', edit_venue_path(venue), class: 'btn btn-mini'
          = link_to 'Destroy', venue, :confirm => 'Are you sure?', :method => :delete, class: 'btn btn-mini'

br

= link_to 'New Venue', new_venue_path, class: 'btn btn-primary'

app/views/venues/new.html.slim
h1 New venue

== render 'form'

br
br
= link_to 'Back', venues_path, class: 'btn'

app/views/venues/show.html.slim
p#notice = notice

p
  strong Title:
  = @venue.name
p
  strong Address:
  = @venue.address
p
  strong Sun from:
  = @venue.sun_from.strftime '%H:%M'
p
  strong Sun to:
  = @venue.sun_to.strftime '%H:%M'
p
  strong Lat:
  = @venue.latitude
p
  strong Long:
  = @venue.longitude
p
  strong Area:
  = @venue.area.name
p
  strong URL:
  = @venue.url
p
  = image_tag @venue.image_url

= link_to 'Edit', edit_venue_path(@venue)
'|
= link_to 'Back', venues_path